"use client";
import React, { useState, useEffect } from 'react';
import CollectionModel from '@/models/CollectionModel';
import Link from 'next/link';
import HEAD from 'next/head';

/**
 * This page will display all the collections available
 * @param collection : variable to store the collection data
 * @returns 
 */
const CollectionPage = ({ collection }) => {

    const model: CollectionModel = new CollectionModel();
    const [collections, setCollections] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            const response = await model.getCollections();
            console.log(response);
            setCollections(response.data);
        }
        fetchData();
    }, []);


    const data = {
        title: "Collection",
        paths: [
            { name: 'Home', href: '/' },
            { name: "Collection", href: `/collection` }
        ]
    }
    return (
        <>
            <HEAD>
                <title>{data.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </HEAD>
            <div>
                <p>
                    Collections Page
                </p>
                {collections.map((collection) => (
                    <div
                        className="py-3 px-5 bg-gray-200 m-2 d-block "
                        key={collection.id}>
                        <Link href={`/collections/${collection.slug}`}>
                            {collection.name}
                        </Link>
                    </div>
                ))}
            </div>
        </>

    );
}

export default CollectionPage;